services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080

  backend:
    build: ./backend/timer-backend
    ports:
      - "8080:8080"
    environment:
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT:-https://localhost:8081}
      COSMOS_KEY: ${COSMOS_KEY:-C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b5MS3e4fqn8pvI/IcrberBAejpSkWg==}
      COSMOS_DATABASE: ${COSMOS_DATABASE:-timer-db}
